### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by mknj** [EXXETA/openapi-cop#352]
After 
```bash
npm i typescript@4.0.5
cd mock
npm i
cd ..
npm i
npm run test
```

i get

```
...
Validating against 7-petstore.yaml ("Test API 7 - Petstore", version: 1.0.0)
Running test...
Sending request GET /pets
Sending request GET /pets/1
Shutting down servers...
      ✔ should respond with validation headers that are ValidationResult: 7-petstore.yaml
Starting proxy server...
Reading output

...
d_for,"___cxa_allocate_exception":___cxa_allocate_exception,"_emscripten_memcpy_big":_emscripten_memcpy_big,"___cxa_end_catch":___cxa_end_catch,"___resumeException":___resumeException,"__ZSt18uncaught_exceptionv":__ZSt18uncaught_exceptionv,"___cxa_begin_catch":___cxa_begin_catch,"_pthread_getspecific":_pthread_getspecific,"__arraySum":__arraySum,"_pthread_once":_pthread_once,"___syscall54":___syscall54,"___unlock":___unlock,"__isLeapYear":__isLeapYear,"_pthread_setspecific":_pthread_setspecific,"___cxa_throw":___cxa_throw,"___cxa_rethrow":___cxa_rethrow,"___syscall6":___syscall6,"_pthread_cleanup_push":_pthread_cleanup_push,"___cxa_pure_virtual":___cxa_pure_virtual,"___syscall140":___syscall140,"___cxa_find_matching_catch":___cxa_find_matching_catch,"___syscall145":___syscall145,"___syscall146":___syscall146,"STACKTOP":STACKTOP,"STACK_MAX":STACK_MAX,"DYNAMICTOP_PTR":DYNAMICTOP_PTR,"tempDoublePtr":tempDoublePtr,"ABORT":ABORT,"cttz_i8":cttz_i8};// EMSCRIPTEN_START_ASM



AssertionError: should show failure to communicate with the target server: expected false to be true
    at ChildProcess.<anonymous> (***/openapi-cop/test/02.integration.test.ts:239:18)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12) {
  showDiff: true,
  actual: false,
  expected: true,
  operator: 'strictEqual'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! openapi-cop@1.1.0 test: `mocha --bail --timeout 60000 --exit build/test/*.test.js`
npm ERR! Exit status 7
```

please describe in the readme how to set up the dev environment and run the tests.

**Comment by michel-zedler** [comment]
Hi @mknj,

test are passing with node v12.22.12.

`nvm install v12.22.12 && nvm use v12.22.12 && (cd mock/ && npm i) && npm i && npm run test`

Later node version seem to be unsupported:
node v14.19.3 (Maintenance LTS) > test error @ 02.integration.test.ts:239:18 (same as above)
node v16.15.1 (Active LTS) > tsc errors
node v18.4.0 (Current) > tsc errors

**Comment by mknj** [comment]
Are there any plans to at least support node 16?

(My current web application does not work anymore if i proxy it through openapi-cop. Some APIs just hang, others fail.)

**Comment by LexLuengas** [comment]
Yes, a node upgrade is on our roadmap. We are aiming to support at least the current active LTS version (16).
